# Cấu hình cho Netlify để build trang admin

[build]
  command = "npm run build"
  publish = "dist"

# Cấu hình chuyển hướng (proxy) cho các API call
[[redirects]]
  # Bất kỳ request nào bắt đầu bằng /api/
  from = "/api/*"
  
  # Sẽ được chuyển hướng đến backend server của bạn
  to = "https://key-manager-backend.onrender.com/:splat"
  
  # Status 200 để làm proxy, không phải redirect
  status = 200

# Quy tắc này đảm bảo routing phía client của React hoạt động
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200