# Netlify configuration file
# This file configures proxy redirects for the API and build settings for keyadmin.

[build]
  base = "keyadmin"
  command = "npm install && npm run build"
  publish = "keyadmin/build"

[[redirects]]
  from = "/api/*"
  to = "https://key-manager-backend.onrender.com/api/:splat"
  status = 200
  force = true
