# Netlify configuration for main frontend app
# Build settings and API proxy configuration

[build]
  command = "npm install && npm run build"  
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

# API proxy redirects to backend
[[redirects]]
  from = "/api/*"
  to = "https://key-manager-backend.onrender.com/api/:splat"
  status = 200
  force = true

# SPA routing fallback  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
