# Cấu hình cho Netlify để build trang admin

[build]
  # Thư mục gốc của trang admin
  base = "keyadmin/"
  
  # Lệnh để cài đặt và build trang admin
  command = "npm install && npm run build"
  
  # Thư mục chứa kết quả sau khi build
  publish = "keyadmin/build/"

# Cấu hình chuyển hướng (proxy) cho các API call
[[redirects]]
  # Bất kỳ request nào bắt đầu bằng /api/
  from = "/api/*"
  
  # Sẽ được chuyển hướng đến backend server của bạn
  to = "https://key-manager-backend.onrender.com/:splat"
  
  # Status 200 để làm proxy, không phải redirect
  status = 200

# Quy tắc này đảm bảo routing phía client của React hoạt động
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200