# Netlify configuration for frontend app with backend proxy

[build]
  command = "npm run build"
  publish = "dist"

# Proxy configuration for backend API calls
[[redirects]]
  from = "/api/*"
  to = "https://key-manager-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Quy tắc này đảm bảo routing phía client của React hoạt động
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200